#!/bin/bash
apt update -y
apt upgrade -y

apt install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

apt update -y
apt upgrade -y

apt install docker-ce -y
service docker start

docker run -p 80:8888 jupyter/scipy-notebook:17aba6048f44

